# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecfa9c8c1c733e24a263e18ef327aee17f7bcbe98c6bbb028e43afb96e8687f048975c609b9c7e723a28f6674e8ca4d7a739a18cb2c78f6288018e685d99e001

test:
  secret_key_base: 458643ed074acee7dfff14589409eafbac01e39fd5750eac3d5d3877dee7390bb8bad90540c9e1f68bd3ed0f95a2705bcf52e3fd7f57dfee397889f200e7234e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
